### ISSUE TITLE
current token is_expired() method?

### ISSUE THREAD

**Issue by wbeange** [firebase/firebase-token-generator-ruby#6]
How do I check if a current token is expired?

**Comment by drtriumph** [comment]
This repo is specifically for the generation of Firebase JWTs. If you decode the token using another library the expiry is easy to find, and then aside from any clock skew between your machine and our servers you should have a pretty good idea if it's valid

**Comment by wbeange** [comment]
Thanks. using https://github.com/progrium/ruby-jwt.

`begin
    JWT.decode("JWT_STRING", "secret")
rescue JWT::ExpiredSignature
    # Signature has expired
end`
